services:
  web:
    build: .
    image: travel-carribe:latest
    ports:
      - '5173:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
